
name: Java CI with Gradle

on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        zip -r ./build/output/ArcanoTechGenesis_client.zip ./src/client/
        zip -r ./build/output/ArcanoTechGenesis_client.zip ./src/client/

    - name: Upload Build
      uses: actions/upload-artifact@v4.6.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/output/*
        
