name: Manual Release with Auto-Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (z. B. 1.0.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set tag name
        id: vars
        run: echo "TAG_NAME=v${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Create ZIP files
        run: |
          mkdir -p release
          zip -r release/ArcanoTechGenesis_client.zip src/client
          zip -r release/ArcanoTechGenesis_server.zip src/server

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          body: "Automatisch generiertes Release für Version ${{ env.TAG_NAME }}"
          files: |
            release/ArcanoTechGenesis_client.zip
            release/ArcanoTechGenesis_server.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
